name: Unit Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  php-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      COMPOSER_NO_INTERACTION: 1
      CI_ENV: github

    strategy:
      matrix:
        php: [7.4]
        dependency-version: [prefer-stable]

    name: P${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer:v1

      - name: SetLocale
        run: |
          php CharsetConverter.php
          localectl status
          sudo localectl set-locale LANG="en_US.UTF-8"
          localectl status         
          php CharsetConverter.php
