name: Unit Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  php-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      COMPOSER_NO_INTERACTION: 1
      CI_ENV: github

    strategy:
      matrix:
        php: [8]
        dependency-version: [prefer-stable]

    name: P${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: conjoon/php-ms-imapuser

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: iconv
          tools: composer:v1
          coverage: none

      - name: SetLocale
        run: |
          composer i --ignore-platform-reqs
          vendor/bin/phpunit
          
